---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(leaflet)
library(sf)
library(tmap)
library(dataRetrieval)

```

```{r}
start_date <- "1970-01-01"
```


## Get NO3 data
```{r}
pCode <- c("00618")

sites_NO3 <- whatWQPdata(stateCd = "NY", 
                            parameterCd = pCode, 
                            startDate = start_date
                            ) %>% 
  
  filter(ResolvedMonitoringLocationTypeName %in% c("Lake, Reservoir, Impoundment"))
```
```{r}
data_NO3 <- readWQPqw(siteNumbers = sites_NO3$MonitoringLocationIdentifier,
                                parameterCd = pCode,
                                startDate = start_date
                                )
```
00673
00666
## Get phosphate data
```{r}
pCode <- c("00666")

sites_PO4 <- whatWQPdata(stateCd = "NY", 
                            parameterCd = pCode, 
                            startDate = start_date
                            ) %>% 
  
    filter(ResolvedMonitoringLocationTypeName %in% c("Lake, Reservoir, Impoundment"))
```

```{r}
data_PO4 <- readWQPqw(siteNumbers = sites_PO4$MonitoringLocationIdentifier,
                                parameterCd = pCode,
                                startDate = start_date
                                )
```


## Join the data

### Select a subset of columns (variables) for the NO3 data
```{r}
data_select_NO3 <- data_NO3 %>% 
  select(ActivityStartDate, MonitoringLocationIdentifier, 
         CharacteristicName_NO3 = CharacteristicName, 
         USGSPCode_NO3 = USGSPCode,
         ResultMeasureValue_NO3 = ResultMeasureValue, 
         ResultMeasure_MeasureUnitCode_NO3 = ResultMeasure.MeasureUnitCode)
```

```{r}
data_select_NO3 <- data_select_NO3 %>% 
  group_by(ActivityStartDate, MonitoringLocationIdentifier) %>% 
  summarize(CharacteristicName_NO3 = first(CharacteristicName_NO3),
            USGSPCode_NO3 = first(USGSPCode_NO3),
            ResultMeasureValue_NO3 = mean(ResultMeasureValue_NO3, na.rm = T),
            ResultMeasure_MeasureUnitCode_NO3 = first(ResultMeasure_MeasureUnitCode_NO3)
            )
```



### Select a subset of columns (variables) for the PO4 data
```{r}
data_select_PO4 <- data_PO4 %>% 
  select(ActivityStartDate, MonitoringLocationIdentifier, 
         CharacteristicName_PO4 = CharacteristicName, 
         USGSPCode_PO4 = USGSPCode,
         ResultMeasureValue_PO4 = ResultMeasureValue, 
         ResultMeasure_MeasureUnitCode_PO4 = ResultMeasure.MeasureUnitCode)
```

```{r}
data_select_PO4 <- data_select_PO4 %>% 
  group_by(ActivityStartDate, MonitoringLocationIdentifier) %>% 
  summarize(CharacteristicName_PO4 = first(CharacteristicName_PO4),
            USGSPCode_PO4 = first(USGSPCode_PO4),
            ResultMeasureValue_PO4 = mean(ResultMeasureValue_PO4, na.rm = T),
            ResultMeasure_MeasureUnitCode_PO4 = first(ResultMeasure_MeasureUnitCode_PO4)
            )
```



### Join the Na and Cl data
```{r}
data_NO3_PO4 <- data_select_NO3 %>% 
  full_join(data_select_PO4)
```
## Join the site info to the chemistry data
```{r}
site_info_select <- sites_NO3 %>% 
  bind_rows(sites_PO4) %>% 
  distinct()
```

```{r}
site_info_select <- site_info_select %>% 
  select(MonitoringLocationIdentifier, 
         MonitoringLocationName, 
         HUCEightDigitCode, 
         ResolvedMonitoringLocationTypeName, 
         StateName, 
         CountyName, 
         lat, 
         lon) %>% 
  distinct()
```

```{r}
data_NO3_PO4 <- data_NO3_PO4 %>% 
  left_join(site_info_select)
```
## Write data to csv
```{r}
write_csv(x = data_NO3_PO4, file = "./data_NO3_PO4.csv")
```


## Make some figures
```{r}
data_NO3_PO4 %>% 
  ggplot(aes(x = ResultMeasureValue_PO4, y = ResultMeasureValue_NO3)) +
  geom_point()
```

```{r}
site_summary <- data_NO3_PO4 %>% 
  group_by(MonitoringLocationIdentifier) %>% 
  summarize(n_samples = n())
```

```{r}
sites2plot <- site_summary %>% 
  filter(n_samples >= 25)
```


```{r}
data_NO3_PO4 %>% 
  filter(MonitoringLocationIdentifier %in% sites2plot$MonitoringLocationIdentifier) %>% 
  
  ggplot(aes(x = ActivityStartDate, y = ResultMeasureValue_NO3, group = MonitoringLocationIdentifier)) +
  geom_point() +
  geom_line() +
  
  facet_wrap(~MonitoringLocationIdentifier, scales =  "free_x")
```


