---
title: "Class notes"
author: "_Mason Stahl_ (ENS-215)"
date: "2026-01-29"
date-format: "MMMM D, YYYY"
format:
  html:
    embed-resources: true
    code-fold: show
    code-tools: 
      source: false
    df-print: paged
    theme:
      light: journal
      dark: darkly
    page-layout: full
    toc: true
    toc-float: true
---

## Revisit the exercises from last class

```{r}
library(tidyverse)
library(gapminder)
```

```{r}
my_gap <- gapminder
```


### EX 1
```{r}
my_gap %>% 
  ggplot(aes(x = year, y = lifeExp, color = continent, size = pop)) +
  geom_jitter(width = 0.5, height = 0, alpha = 0.5)
```

### EX 2
```{r}
my_gap %>% 
  filter(year == 2007) %>% 
  
  ggplot(aes(x = continent, y = lifeExp)) +
  geom_boxplot(fill = "lightblue") +
  geom_jitter(alpha = 0.5, width = 0.1, height = 0)
```



### EX 3

```{r}
top_2 <- my_gap %>% 
  filter(year == 2007) %>% 
  top_n(n = 2, lifeExp) %>% 
  select(country)

bottom_2 <- my_gap %>% 
  filter(year == 2007) %>% 
  top_n(n = -2, lifeExp) %>% 
  select(country)

```


```{r}
my_gap %>% 
  filter(country == top_2$country | country == bottom_2$country) %>% 
  
  ggplot(aes(x = year, y = lifeExp, color = country)) +
  geom_point() +
  geom_line()
```

## Start today's work here

```{r}

```



