---
title: "Classwork"
author: "_Mason Stahl_ (ENS-215)"
date: "2026-01-20"
date-format: "MMMM D, YYYY"
format:
  html:
    embed-resources: true
    code-fold: show
    code-tools: 
      source: false
    df-print: paged
    theme:
      light: journal
      dark: darkly
    page-layout: full
    toc: true
    toc-float: true
---

## Revisiting exercises from last Thursday
```{r}
library(tidyverse)
library(gapminder)
```

```{r}
gap_data <- gapminder
```


```{r}
my_continents <- c("Asia", "Africa")

table_01 <- gap_data %>% 
  filter(year >= 1980) %>% 
  #filter(continent == "Asia"| continent == "Africa")
  filter(continent %in% my_continents) %>% 
  arrange(lifeExp)

table_01
```


```{r}
avg_life <- mean(gap_data$lifeExp)

avg_life
```

```{r}

table_02 <- gap_data %>% 
  filter(lifeExp > avg_life, 
         pop > 20*10^6
         )

table_02
```


## Let's start today's lesson

```{r}
my_gap <- gapminder
```


```{r}

my_gap <- my_gap %>% 
  mutate(tot_gdp = gdpPercap * pop)

```

first exercise
```{r}
my_gap %>% 
  filter(year == 1952) %>% 
  arrange(-tot_gdp)
```


```{r}
my_gap %>% 
  filter(year == 2007) %>% 
  arrange(-tot_gdp)
```


Vector functions with mutate
```{r}
my_gap <- my_gap %>% 
  mutate(log10_pop = log10(pop))
```


```{r}
my_gap <- my_gap %>% 
  mutate(gdp_percap_ratio = gdpPercap/max(gdpPercap))
```


Let's try out the if_else() function
```{r}
my_gap <- my_gap %>% 
  mutate(income_status = if_else(gdpPercap > 7500, "higher-income", "lower-income")
           
           )
```


Test out case_when() function

```{r}
my_gap <- my_gap %>% 
  mutate(income_status = case_when(gdpPercap > 7500 ~ "high-income",
                                   gdpPercap > 3500 & gdpPercap <= 7500 ~ "middle-income",
                                   gdpPercap <= 3500 ~ "low-income"
    
    
  )
         
         )
```


```{r}
table_01 <- my_gap %>% 
  filter(year == 1952) %>% 
  top_n(10, lifeExp)

table_01
```



