---
title: "R Notebook"
output: html_notebook
---
https://wcmbishop.github.io/rayshader-demo/

```{r}
library(rayshader)
```

```{r}
source("get_usgs_elevation_data.R")
source("define_image_size.R")
```


42.768403, -73.997889
42.862791, -73.873456
```{r}
# define bounding box with longitude/latitude coordinates
bbox <- list(
  p1 = list(long = -73.997889, lat = 42.768403), # bottom-left
  p2 = list(long = -73.873456, lat = 42.862791)   # top-right
)
```


```{r}
image_size <- define_image_size(bbox, major_dim = 600)
```


```{r}
# download elevation data
elev_file <- file.path("Data", "sf-elevation.tif")
get_usgs_elevation_data(bbox, size = image_size$size, file = elev_file,
                        sr_bbox = 4326, sr_image = 4326)
```


```{r}
elev_img <- raster::raster(elev_file)
```

```{r}
raster::plot(elev_img)
```

```{r}
elmat <- matrix(
  raster::extract(elev_img, raster::extent(elev_img), buffer = 1000), 
  nrow = ncol(elev_img), ncol = nrow(elev_img)
)
```



```{r}
elmat %>%
  sphere_shade(sunangle = 315, texture = "bw") %>%
  plot_map()
```



```{r}
elmat %>%
  sphere_shade(texture = "bw") %>%
  #add_water(detect_water(elmat), color = "blue") %>%
  add_shadow(ray_shade(elmat, zscale = 3), 0.5) %>%
  add_shadow(ambient_shade(elmat), 0) %>%
  plot_3d(elmat, zscale = 3, fov = 0, theta = 0, zoom = 0.75, phi = 45, windowsize = c(1000, 800))
Sys.sleep(0.2)
render_snapshot(clear=TRUE)
```


```{r}
filename_movie = tempfile()

elmat %>% 
  sphere_shade(texture="imhof1") %>%
  add_water(detect_water(elmat), color = "blue") %>%
  plot_3d(elmat, zscale=3, waterlinecolor="white", waterlinealpha=0.5)
  render_movie(filename = filename_movie)
```


