---
title: "Graphical display of data distributions"
author: "ENS-215"
date: "09-Feb-2022"
output:
  html_document:
    theme: spacelab
    df_print: paged
---

<br/>

```{r message=FALSE, echo=FALSE, warning=FALSE}
library(tidyverse)
library(stats)
library(scales)
```

### All of the graphics below display the exact same data.  The dataset plotted in the graphics below contains 100,000 values randomly drawn from a Normal distribution with a mean = 6 and standard deviation = 1

```{r echo=FALSE}
vec_norm <- tibble(values = rnorm(n = 1*10^5, mean = 6, sd = 1))
```


```{r echo=FALSE}

qv <- quantile(vec_norm$values, probs = c(0.25, 0.50, 0.75))

```


```{r echo=FALSE}
vec_norm %>% 
  ggplot(aes(y = 1, x = values)) +
  geom_jitter(width = 0, alpha = 0.02) +
  theme_classic() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  labs(y = "",
       x = "Value",
      title = "Jitter plot",
       subtitle = "Sample of 100,000 values from Normal distribution (mean = 6, sd = 1)")

```




```{r echo=FALSE}
vec_norm %>% 
  ggplot(aes(y = values)) +
  geom_boxplot() +
  theme_classic() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  labs(y = "Value",
       x = "",
       title = "Box plot",
       subtitle = "Sample of 100,000 values from Normal distribution (mean = 6, sd = 1)") +
  coord_flip()

```


```{r echo=FALSE}
vec_norm %>% 
  ggplot(aes(values)) +
  geom_histogram(fill = "grey", bins = 100) +
  theme_classic() +
  labs(x = "Value",
       y = "Counts",
       title = "Histogram",
       subtitle = "Sample of 100,000 values from Normal distribution (mean = 6, sd = 1)",
       caption = "Dashed lines represent 25th and 75th percentile, solid line represents 50th") +
  geom_vline(xintercept = qv[1], linetype = "dashed") +
  geom_vline(xintercept = qv[2], linetype = "solid", color = "blue") +
  geom_vline(xintercept = qv[3], linetype = "dashed") 
```


```{r echo=FALSE}
vec_norm %>% 
  ggplot(aes(values)) +
  geom_density(fill = "grey") +
  theme_classic() +
  labs(x = "Value",
       y = "Density",
       title = "Density plot",
       subtitle = "Sample of 100,000 values from Normal distribution (mean = 6, sd = 1)",
       caption = "Dashed lines represent 25th and 75th percentile, solid line represents 50th") +
  geom_vline(xintercept = qv[1], linetype = "dashed") +
  geom_vline(xintercept = qv[2], linetype = "solid", color = "blue") +
  geom_vline(xintercept = qv[3], linetype = "dashed") 
```


```{r echo=FALSE}
vec_norm %>% 
  ggplot(aes(x = cume_dist(values), y = values))  +
  geom_line() +
  theme_classic() +
  labs(x = "f-value",
       y = "Value",
       title = "Quantile plot",
       subtitle = "Sample of 100,000 values from Normal distribution (mean = 6, sd = 1)",
       caption = "Dashed lines represent 25th and 75th percentile, solid line represents 50th") +
  geom_hline(yintercept = qv[1], linetype = "dashed") +
  geom_hline(yintercept = qv[2], linetype = "solid", color = "blue") +
  geom_hline(yintercept = qv[3], linetype = "dashed") 
```

```{r echo=FALSE}
vec_norm %>% 
  ggplot(aes(x = cume_dist(values), y = values))  +
  geom_line() +
  coord_flip() +
  theme_classic() +
  labs(y = "Value",
       x = "Cumulative probability",
       title = "Cumulative distribution plot",
       subtitle = "Sample of 100,000 values from Normal distribution (mean = 6, sd = 1)",
       caption = "Dashed lines represent 25th and 75th percentile, solid line represents 50th") +
  geom_hline(yintercept = qv[1], linetype = "dashed") +
  geom_hline(yintercept = qv[2], linetype = "solid", color = "blue") +
  geom_hline(yintercept = qv[3], linetype = "dashed") 
  
```