---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(GSODR)

library(dataRetrieval)
library(lubridate)

library(ggrepel)

library(leaflet)
```

# get streamflow data
02354500
02357000

06867500 
```{r}
site_to_get <- "06867500"

df_stream_data <- readNWISdv(siteNumbers = site_to_get,
                             parameterCd = c("00060"))
```

```{r}
df_stream_data <- df_stream_data %>% 
  renameNWISColumns()
```


```{r}
streamflow_site_info <- readNWISsite(siteNumbers = site_to_get)
```



# get precipitation data
999999-63828

```{r}
load(system.file("extdata", "isd_history.rda", package = "GSODR"))
```

```{r}
met_long_record <- isd_history %>% 
    mutate(y_start = year(ymd(BEGIN)), 
           y_end =  year(ymd(END)) 
         ) %>% 
  
  filter(y_start <= 1970,
         y_end >= 2020, 
         COUNTRY_NAME == "UNITED STATES"
          
         
         ) %>% 
  
  leaflet() %>% 
  addProviderTiles(provider = providers$OpenStreetMap) %>% 
  addMarkers(lng = ~ LON, lat = ~ LAT, popup = ~ STNID)
```



```{r}
nearby_met_stations <- nearest_stations(LAT = streamflow_site_info$dec_lat_va,
                                        LON = streamflow_site_info$dec_long_va,
                                        distance = 75)
```

```{r}
met_site_to_use <- isd_history %>% 
  filter(STNID %in% nearby_met_stations) %>% 
  filter(ymd(END) - ymd(BEGIN) == max(ymd(END) - ymd(BEGIN))) %>% 
  
  mutate(y_start = year(ymd(BEGIN)), 
         y_end =  year(ymd(END)) 
         )
```


```{r}
met_df <- get_GSOD(station = met_site_to_use$STNID, years = met_site_to_use$y_start:met_site_to_use$y_end)

#met_df <- get_GSOD(station = "999999-63828", years = 2003:2021)
```



# double mass curve


## Annual streamflow
```{r}
df_stream_summary <- df_stream_data %>% 
  mutate(YEAR = year(Date)) %>% 
  
  group_by(YEAR) %>% 
  summarize(flow_annual_mean = mean(Flow, na.rm = T),
            n_days = n()
            ) %>% 
  
  filter(n_days >= 365) %>% 
  
  select(-n_days)
```

## Annual precip


```{r}
df_met_summary <- met_df %>% 
  group_by(YEAR) %>% 
  summarize(precip_tot = sum(PRCP, na.rm = T),
            n_days = sum(!is.na(PRCP))
            ) %>% 
  
  filter(n_days >= 365) %>% 
  
  select(-n_days)
  
```



```{r}
df_precip_flow <- df_met_summary %>% 
  inner_join(df_stream_summary, by = "YEAR")
```

```{r}
df_precip_flow <- df_precip_flow %>% 
  mutate(cumul_precip = cumsum(precip_tot),
         cumul_flow = cumsum(flow_annual_mean)
         )
```



```{r}
df_precip_flow %>% 
  ggplot(aes(x = cumul_precip, y = cumul_flow)) +
  geom_point() +
  
  geom_text_repel(aes(label = YEAR), box.padding = 0.75)
```



