---
title: "EPA Fuel Economy Lab"
author: "Mason Stahl"
output: html_document
---


### Load in packages
```{r}
library(tidyverse)
```
### Load in our data
```{r}
fuel_data <- mpg
```



### Examine the data
```{r}
str(fuel_data)
```

```{r}
n_rows <- nrow(fuel_data)
n_cols <- ncol(fuel_data) 
```

```{r}
dim(fuel_data)[2]
```

Let's go ahead and summarize the data
```{r}
summary(fuel_data)
```
Most fuel efficient on hwy was 44 mpg
Least fuel efficient on hwy was 12 mpg
Avg fuel efficiency for city was 16.86 mpg


### Add a new column

first way
```{r}
fuel_data$hwy2cty <- fuel_data$hwy/fuel_data$cty
```

second way
```{r}
fuel_data <- mutate(fuel_data, hwy2cty = hwy/cty)
```

```{r}
min(fuel_data$hwy2cty)
max(fuel_data$hwy2cty)
```

### Examine factors: Displacement

```{r}
ggplot(data = fuel_data) +
  geom_point(aes(x = displ, y = hwy))
```

```{r}
ggplot(data = fuel_data) +
  geom_point(aes(x = displ, y = hwy, color = class))
```

```{r}
ggplot(data = fuel_data) +
  geom_point(aes(x = displ, y = hwy, color = year))
```

```{r}
ggplot(data = fuel_data) +
  geom_point(aes(x = displ, y = hwy)) +
  facet_wrap(~class)
```

Let's add one more variable
```{r}
us_makes <- c("chevrolet","dodge","ford","jeep",
              "lincoln","mercury","pontiac"
              )
```

```{r}
fuel_data <- mutate(fuel_data, 
                    region = if_else(manufacturer %in% us_makes, "US", "Foreign"))
```


```{r}
ggplot(data = fuel_data) +
  geom_boxplot(aes(x = region, y = hwy))
```


