---
title: "Proposal feedback and kick-off of analysis"
author: "ENS-215"
date: "Winter 2022"
output:
  html_document:
    df_print: paged
    theme: spacelab
---


## Overview and goals for today's lab
I've gone through your proposals and I will come around and meet with each of you during today's lab.  I will provide my feedback on your proposed project and we can discuss any adjustments that might be necessary to ensure your success.  


You should have the following ready when I come around:

  + Your project folder and any sub-folders.  I need to see that your project is organized and that you've created an R Project.
  + The dataset(s) you will use.  Have these files open and ready to examine.  Be ready to show me where you got the data.
  + Any R Notebooks that you've put together thus far to begin loading the data in to R and to begin performing your analysis.
      + In your R Notebooks you should show me that you are using **relative paths** when reading or writing files.
  + If you have any questions or need guidance about any aspect of the project generally or your project specifically let me know and we will work through it.


<br/>

Once we have discussed your project you will continue working on your final project in lab.  I will be moving around and periodically checking in to provide help/guidance and to see how everything is going.  Take advantage of today's lab to get help/feedback from me and your classmates.  

<br/>

## Important Reminders 

+ Remember to always open your R Project corresponding to your final project.  This sets your working directory to your Final Project directory.
+ Stay organized and document your work.  
    + Create **readme** files that record exactly where you obtained your data from and any other relevant info regarding the data.
    + Clearly document your code with comments and notes.  This is important in conducting high-quality and reproducible work.  Also I will be grading you on this.
    + Name R files and your data files intelligently
        + Do not have spaces in names, excessively long names,...
        + Name files so that they can easily be identified (e.g. use informative names)
+ Practice good coding style -- this will make your code much easier to debug, edit, and read (also I grade you on this).  See the [tidyverse style guide (Ch. 1, 2, 4, 5)](https://style.tidyverse.org/) for tips.  
+ Save and backup your work -- we don't want anyone to lose any of their hardwork.  If you use cloud backup (e.g. Carbonite, Google Backup and Sync,...) you are all set.  If not, you can save you periodically backup your project folder to an external hard drive or flashdrive.  
+ Make sure to work on your project outside of lab.  Remember it is an important part of your final course grade and requires significant work outside of lab.  
+ Have fun and enjoy the work.  This is your chance to explore a topic that interests you and to demonstrate the skills you've learned in this class.


    


