---
title: "Final projects: last steps"
author: "ENS-215"
date: "1-Mar-2022"
output:
  html_document:
    df_print: paged
    theme: spacelab
    toc: yes
    toc_float: yes
---


<br/>

Today is the last lab where we will work on your final project.  In next week's lab (week 10) you will present your completed project to me and your classmates.  

Look back at the [project guidelines](https://stahlm.github.io/ENS_215/Winter_2022/Labs/Lab_Final_Project.html) to ensure that the your final project conforms with all of the stated guidelines and that you properly submit your project.  


<br/>

### Important notes

+ Remember that you are to **submit a folder containing everything needed to run your code and produce your knitted final project**.  Thus your R notebook and all required data should be in this folder (and its sub-folders).  Recall that you should be using relative paths in your code -- I need to be able to download your folder and run the code as is.   I will provide you with two submission links on Nexus.  
    + One of the links is where you will upload a zip-file of your complete project folder (all your code, data, and your knitted output).  
    + The other link is where you will submit just your knitted file (note this should be your **.html** and not your **.html.nb** file) -- this way I can quickly bring up your presentation file during final presentations in Lab (Week 10).

+ Your presentation to the class should be ~10 minutes.  In your presentation you will introduce your topic and dataset, give the necessary background information, discuss your analytical approach, and summarize your results and findings.  You should give a practiced and polished presentation to the class -- the quality of your presentation is part of the overall assessment.  


