---
title: "Exploring Environmental Data (ENS-215)"
date: "Winter 2022"
output:
  html_document:
    theme: spacelab
    toc: yes
    toc_float: yes
---




***

| [ENS-215](https://stahlm.github.io/ENS_215/Winter_2022/Home.html)  | [Homework](https://stahlm.github.io/ENS_215/Winter_2022/HW.html)  | [Syllabus](https://stahlm.github.io/ENS_215/Winter_2022/Syllabus.html)  |
|:-------:|:------:|:--------:|
|      |     |        |       |



***

### Week 1
#### Readings
* [**ModernDive Ch: 1, 2**](https://moderndive.com/)
* [**R for Data Science (R4DS) Ch: 1**](https://r4ds.had.co.nz/)  


#### Assignments
**1. Download R and RStudio:**
You will first need to download R and then RStudio.  To download R go to [this link](https://cran.rstudio.com/) and download R.  You will see links for Mac and Windows users (make sure to select the appropriate one for your computer).  Download the program and then install it.

Once you've downloaded and installed R, then you will need to get RStudio.  Go to [this link](https://www.rstudio.com/products/rstudio/download/#download) and download the "Installer for Supported Platform" that corresponds to your computer (i.e. Mac or Windows).  Download and install the software.

  + Assigned: 3-Jan
  + Due: 5-Jan  

**2. Accept the invite to our DataCamp class and complete "_Introduction to R_"**  

  + Assigned: 3-Jan
  + Due: 10-Jan
  + **Note:** You should accept the DataCamp invitation immediately 


**3.  Get a binder to hold your course notes and bring to all future classes**  

  + Assigned: 3-Jan
  + Due: 12-Jan



***