---
title: "R Notebook"
output: html_notebook
---


https://wcmbishop.github.io/rayshader-demo/

```{r}
library(rayshader)
```

```{r}
getwd()
```


```{r}
source("../functions/get_usgs_elevation_data.R")
source("../functions/define_image_size.R")

```


42.768403, -73.997889
42.862791, -73.873456
```{r}
# define bounding box with longitude/latitude coordinates (Schenectady)
bbox <- list(
  p1 = list(long = -73.997889, lat = 42.768403), # bottom-left
  p2 = list(long = -73.873456, lat = 42.862791)   # top-right
)
```


```{r}
image_size <- define_image_size(bbox, major_dim = 600)
```


```{r}
# download elevation data
elev_file <- file.path("../data", "schenectady-elevation.tif")
get_usgs_elevation_data(bbox, size = image_size$size, file = elev_file,
                        sr_bbox = 4326, sr_image = 4326)
```


```{r}
elev_img <- raster::raster(elev_file)
```




```{r}
raster::plot(elev_img)
raster::contour(elev_img, levels = seq(50,150, by = 5), 
                add = T)
```

```{r}
elmat <- matrix(
  raster::extract(elev_img, raster::extent(elev_img), buffer = 1000), 
  nrow = ncol(elev_img), ncol = nrow(elev_img)
)
```

```{r}
elmat %>%
  sphere_shade(sunangle = 315, texture = "bw") %>%
  add_overlay(generate_contour_overlay(elmat))  %>%
  #add_water(detect_water(elmat),color="imhof3") %>%
  plot_map()
```


```{r}
elmat %>%
 height_shade() %>%
 add_shadow(ray_shade(elmat,zscale=50),0.3) %>%
 add_overlay(generate_contour_overlay(elmat))  %>%
 #add_overlay(generate_contour_overlay(elmat, linewidth=2, nlevels=10,
 #                                    height = nrow(elmat)*2, color="black",
 #                                    width  = ncol(elmat)*2), alphalayer=0.5) %>%
 plot_map()
```


```{r}
elmat %>%
  sphere_shade(texture = "imhof4") %>%
  #add_water(detect_water(elmat), color = "blue") %>%
  add_shadow(ray_shade(elmat, zscale = 3), 0.5) %>%
  add_shadow(ambient_shade(elmat), 0) %>%
  add_overlay(generate_contour_overlay(elmat, linewidth = 2))  %>%
  plot_3d(elmat, zscale = 1, fov = 0, theta = -30, zoom = 0.75, phi = 45, windowsize = c(1000, 800))
Sys.sleep(0.2)
#render_depth(focus = 0.6, focallength = 10, clear = TRUE)
render_snapshot(clear=TRUE)
```


```{r}
montereybay %>%
 height_shade() %>%
 add_shadow(ray_shade(montereybay,zscale=50),0.3) %>%
 add_overlay(generate_contour_overlay(montereybay, linewidth=2, nlevels=100,
                                      height = nrow(montereybay)*2, color="black",
                                      width  = ncol(montereybay)*2), alphalayer=0.5) %>%
 plot_map()
```


```{r}
closeAllConnections()
```



