---
title: "R Notebook"
output: html_notebook
---

42.787780, -73.836209


```{r}
library(rayshader)
library(sf)
library(tmap)
```



```{r}
source("../functions/get_usgs_elevation_data.R")
source("../functions/define_image_size.R")

```


42.768403, -73.997889
42.862791, -73.873456
```{r}
# define bounding box with longitude/latitude coordinates (Schenectady)
bbox <- list(
  p1 = list(long = -73.836209 + 0.11, lat = 42.787780 - 0.11/1.5), # bottom-left
  p2 = list(long = -73.836209 - 0.11, lat = 42.787780 + 0.11/2)   # top-right
)
```


```{r}
image_size <- define_image_size(bbox, major_dim = 600)
```


```{r}
# download elevation data
elev_file <- file.path("../data", "lishakill-elevation.tif")
get_usgs_elevation_data(bbox, size = image_size$size, file = elev_file,
                        sr_bbox = 4326, sr_image = 4326)

closeAllConnections()
```


```{r}
elev_img <- raster::raster(elev_file)
```



```{r}
shape_watershed <- st_read("../data/lisha_kill_watershed/area-of-interest.shp", stringsAsFactors = FALSE)

```



```{r}
raster::plot(elev_img)
raster::contour(elev_img, levels = seq(50,150, by = 10), 
                add = F)
```




```{r}
tm_shape(elev_img) +
  tm_raster(style = "cont") +
  
tm_shape(shape_watershed) +
  tm_borders(col = "black")
```

```{r}
raster_elev_LK <- raster::mask(elev_img,
                                    shape_watershed)
```

```{r}
raster::plot(raster_elev_LK)
```



```{r}
raster_elev_LK <- raster::crop(raster_elev_LK,
                                    shape_watershed)
```




```{r}
raster::plot(raster_elev_LK)
```





```{r}
elmat = raster_to_matrix(raster_elev_LK)
```



```{r}
elmat %>%
  sphere_shade(sunangle = 315, texture = "bw") %>%
  #add_overlay(generate_contour_overlay(elmat))  %>%
  #add_water(detect_water(elmat),color="imhof3") %>%
  plot_map()
```






```{r}
raster::crs(elev_img) <- "+proj=longlat +ellps=WGS84 +datum=WGS84"
```

```{r}
elmat = raster_to_matrix(elev_img)
```


```{r}
bottom_left <- c(y = bbox$p1[[1]],x= bbox$p1[[2]])
top_right <- c(y = bbox$p2[[1]], x= bbox$p2[[2]])
```



```{r}
extent_latlong = sp::SpatialPoints(rbind(bottom_left, top_right), 
                 proj4string=sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84"))
```





```{r}
attr(elmat, "extent") = extent_latlong
attr(elmat, "crs") = raster::crs(elev_img)
attr(elmat, "rayshader_data") = TRUE
```

```{r}
shape_watershed = sf::st_crop(shape_watershed, attr(elev_img,"extent"))
```


```{r}
elmat %>%
  sphere_shade(sunangle = 315, texture = "bw") %>%
  add_overlay(generate_polygon_overlay(shape_watershed,  linecolor = "blue",
                                   extent = raster::extent(elev_img), heightmap = elmat),
              alphalayer=0.7)  %>%

  #add_water(detect_water(elmat),color="imhof3") %>%
  plot_map()
```

```{r}
elmat %>%
  sphere_shade(texture = "imhof4") %>%
  #add_water(detect_water(elmat), color = "blue") %>%
  add_shadow(ray_shade(elmat, zscale = 3), 0.5) %>%
  add_shadow(ambient_shade(elmat), 0) %>%
  add_overlay(generate_polygon_overlay(shape_watershed,  
                                       linecolor = "blue",
                                       extent = raster::extent(elev_img), heightmap = elmat),   
              alphalayer=0.7)  %>%
  
  plot_3d(elmat, zscale = 1, fov = 0, theta = -30, zoom = 0.75, phi = 45, windowsize = c(1000, 800))
Sys.sleep(0.2)
#render_depth(focus = 0.6, focallength = 10, clear = TRUE)
render_snapshot(clear=TRUE)
```



