---
title: "Hydrologic measurements and water balances"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: no
---

<br/>

Hydrologic data for the East Canada Creek watershed (located about 30 miles west of Schenectady) is shown below.

+ Streamflow data is from [USGS gage 01348000](https://waterdata.usgs.gov/nwis/nwismap/?site_no=01348000&agency_cd=USGS)    
+ Precipitation data was obtained from [CoCoRaHS](https://www.cocorahs.org/ViewData/ListDailyPrecipReports.aspx) for Herkimer County   
+ Groundwater data is from USGS well [430930074290301](https://waterdata.usgs.gov/nwis/inventory/?site_no=430930074290301&agency_cd=USGS)

<br/>  

```{r echo = F}
# 

knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo = F, fig.width = 9.5, fig.height = 3.25)
```


```{r}
library(tidyverse)
library(dygraphs)
```

```{r}
date_start <- "2019-01-01"
date_end <- "2019-12-31"
```


```{r}
# Download daily USGS 01348000 EAST CANADA CREEK AT EAST CREEK NY

data_streamflow <- dataRetrieval::readNWISdv(siteNumbers = "01348000", 
                                        parameterCd  ="00060",
                                        startDate = date_start, endDate = date_end)

```

```{r}
data_streamflow <- data_streamflow %>% 
  rename(streamflow__cfs = X_00060_00003)
```



```{r}
data_gw <- dataRetrieval::readNWISdv(siteNumbers = "430930074290301", 
                                        parameterCd  ="72019",
                                        startDate = date_start, endDate = date_end)
```

```{r}
land_elevation_ft <- 1606.72

data_gw <- data_gw %>% 
  rename(depth_to_wt__ft = X_72019_00003) %>% 
  mutate(groundwater_elevation = land_elevation_ft - depth_to_wt__ft)
```



```{r}
data_precip <- readr::read_csv("http://data.cocorahs.org/export/exportreports.aspx?ReportType=Daily&dtf=1&Format=CSV&State=NY&County=HR&ReportDateType=reportdate&StartDate=1/1/2019&EndDate=12/31/2019&TimesInGMT=False")
```

```{r}
data_precip <- data_precip %>% 
  mutate(TotalPrecipAmt = if_else(TotalPrecipAmt == "T", 0,as.numeric(TotalPrecipAmt))) %>% 
  rename(Precip__inches = TotalPrecipAmt)
```


```{r}
data_precip <- data_precip %>% 
  group_by(ObservationDate) %>% 
  summarize(Precip__inches = mean(Precip__inches, na.rm = T))
```


```{r}
data_precip <- data_precip %>% 
  select(Date = ObservationDate, Precip__inches)
```


```{r}
data_streamflow <- data_streamflow %>% 
  select(Date, streamflow__cfs)

data_gw <- data_gw %>% 
  select(Date, groundwater_elevation)
  
```


```{r}
data_all <- data_streamflow %>% 
  left_join(data_gw) %>% 
  left_join(data_precip)
```



```{r}
data_all_ts <- xts::xts(data_all[,2:4], order.by = data_all$Date)
```



```{r}
dygraph(data_all_ts[,3], 
        ylab = "Precip [inches]", group = "hydro") %>% 
  dySeries("Precip__inches", label = "Precipitation", stepPlot = T, color = "blue") %>% 
  
  dyOptions(drawGrid = T, fillGraph = TRUE, fillAlpha = 0.4)
  
```


```{r}
dygraph(data_all_ts[,1], 
        ylab = "Streamflow [cfs]", group = "hydro") %>% 
  dySeries("streamflow__cfs", label = "Streamflow", stepPlot = F, color = "green") %>% 
  
  dyOptions(drawGrid = T)
```



```{r}
dygraph(data_all_ts[,2], 
        ylab = "Groundwater elevation [ft]", group = "hydro") %>% 
  dySeries("groundwater_elevation", label = "Groundwater level", stepPlot = F, color = "black") %>% 
  dyRangeSelector(height = 40) %>% 
  dyOptions(drawGrid = T)
```


<br/>

***
| | |
|--|--|
| _Mason Stahl (Union College)_ |  |