---
title: "Exploring Environmental Data (ENS-215)"
output:
  html_document:
    theme: spacelab
    toc: yes
    toc_float: yes
---


***
|  [ENS-215](https://stahlm.github.io/ENS_215/Winter_2020/Home.html) | [Homework](https://stahlm.github.io/ENS_215/Winter_2020/HW.html) | [Syllabus](https://stahlm.github.io/ENS_215/Winter_2020/Website/Syllabus.html) |
|---|------------|-----------|



### Week 10
#### Extra credit assignment (optional) 
1. DataCamp **_Working with Geospatial Data in R_** chapters **3** ("Raster data and color") and **4** ("Data import and projections")
    + Assigned: 11-Mar
    + Due: 18-Mar

***

### Week 9
#### Readings
* [**R for Data Science (R4DS) Ch: 19**](https://r4ds.had.co.nz) (Optional reading)

#### Assignments 
1. DataCamp **_Working with Geospatial Data in R_** chapters **1** ("Basic mapping with ggplot2 and ggmap") and **2** ("Point and polygon data")
    + Assigned: 4-Mar
    + Due: 13-Mar


***

### Week 8
#### Readings
* [**R for Data Science (R4DS) Ch: 27 and 28**](https://r4ds.had.co.nz)
* [**Finish reading ModernDive Ch: 6**](https://moderndive.com/)

#### Assignments 
1. DataCamp **_Modeling with Data in the Tidyverse_** chapters **3** ("Modeling with Multiple Regression
") and **4** ("Model Assessment and Selection")
    + Assigned: 25-Feb
    + Due: 4-Mar


***

### Week 7
#### Readings
* [**ModernDive Ch: 6**](https://moderndive.com/)

#### Assignments 
1. DataCamp **_Modeling with Data in the Tidyverse_** chapters **1** ("Introduction to Modeling") and **2** ("Modeling with Basic Regression")
    + Assigned: 15-Feb
    + Due: 25-Feb

***

### Week 6
#### Readings
* [**Tidyverse style guide, Chapters 1, 2, 4**](https://style.tidyverse.org/)
    + Excellent guide to proper usage of style, formatting, and syntax in R.  Read this with care and where applicable you should begin implementing these style tips in your code.  Note that "style" is more than just cosmetic -- good style makes your code human readable and makes sharing and editing code significantly more efficient and less prone to error.  

#### Assignments 
1. Final project proposal
    + Assigned: 7-Feb
    + Due: 13-Feb  
    
You should Knit your proposal to an `.html` file and submit it on Nexus.  

***

### Week 5
#### Readings
* [**ModernDive Ch: 4**](https://moderndive.com/)
* [**R for Data Science (R4DS) Ch: 12**](https://r4ds.had.co.nz/) (the R4DS reading is optional, though strongly recommended) 

#### Assignments 
1. DataCamp **_Working with Data in the Tidyverse_** chapters **1** ("Explore your data") and **2** ("Tame your data
")
    + Assigned: 1-Feb
    + Due: 6-Feb
  
2. DataCamp **_Working with Data in the Tidyverse_** chapters **3** ("Tidy your data") and **4** ("Transform your data")
    + Assigned: 1-Feb
    + Due: 8-Feb

***


### Week 4
#### Readings
* [**ModernDive Ch: 3**](https://moderndive.com/)
* [**R for Data Science (R4DS) Ch: 3**](https://r4ds.had.co.nz/) (the R4DS reading is optional, though strongly recommended) 

#### Assignments 
1. DataCamp **_Data Visualization with ggplot2 (Part 1)_** chapters **1** ("Introduction") and **2** ("Data")
    + Assigned: 25-Jan
    + Due: 30-Jan
  
2. DataCamp **_Data Visualization with ggplot2 (Part 1)_** chapters **3** ("Aesthetics") and **4** ("Geometries")
    + Assigned: 25-Jan
    + Due: 1-Feb

***

### Week 3
#### Readings
* [**ModernDive Ch: 5**](https://moderndive.com/)
* [**R for Data Science (R4DS) Ch: 5**](https://r4ds.had.co.nz/) (the R4DS reading is optional, though I stronly recommend it as it is very helpful) 

#### Assignments
1. DataCamp **_Introduction to the Tidyverse_** chapters **1** ("Data wrangling") and **2** ("Data visualization")

    + Assigned: 18-Jan
    + Due: 23-Jan

2. DataCamp **_Introduction to the Tidyverse_** chapter **3** ("Grouping and summarizing")

    + Assigned: 18-Jan
    + Due: 25-Jan
  
***

### Week 2

#### Assignments
**1. Complete the "_Conditionals and Control Flow_" and "_Loops_" lessons in the DataCamp "_Intermediate R course_" **  

  + Assigned: 11-Jan
  + Due: 16-Jan
  
**2. Complete the "_Functions_" lesson in the DataCamp "_Intermediate R course_" **

  + Assigned: 14-Jan
  + Due: 18-Jan

***

### Week 1
#### Readings
* [**ModernDive Ch: 1, 2**](https://moderndive.com/)
* [**R for Data Science (R4DS) Ch: 1**](https://r4ds.had.co.nz/)  


#### Assignments
**1. Download R and RStudio:**
You will first need to download R and then RStudio.  To download R go to [this link](https://cran.rstudio.com/) and download R.  You will see links for Mac and Windows users (make sure to select the appropriate one for your computer).  Download the program and then install it.

Once you've downloaded and installed R, then you will need to get RStudio.  Go to [this link](https://www.rstudio.com/products/rstudio/download/#download) and download the "Installer for Supported Platform" that corresponds to your computer (i.e. Mac or Windows).  Download and install the software.

  + Assigned: 7-Jan
  + Due: 9-Jan  

**2. Accept the invite to our DataCamp class and complete "_Introduction to R_"**  

  + Assigned: 7-Jan
  + Due: 14-Jan

**3. Sign up for RStudio Cloud**  

You will recieve an invitation to join our RStudio Cloud group.  You should accept this invitation and create an account if you haven't done so already.  

  + Assigned: 7-Jan
  + Due: 9-Jan
  
**4.  Get a binder to hold your course notes and bring to all future classes**  

  + Assigned: 7-Jan
  + Due: 14-Jan


**5. (Optional) Complete Chapter 1 "Orientation" in the DataCamp "_Working with the RStudio IDE (Part 1)_"**

  + This is optional but strongly recommended.  It will help you understand RStudio much better.

***