---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(osmdata)
library(tigris)
library(sf)
library(tmap)
library(osmplotr)
library(tmaptools)
library(OpenStreetMap)
library(ggpomological)
library(metR)

library(ceramic)
Sys.setenv(MAPBOX_API_KEY = "pk.eyJ1Ijoic3RhaGxtIiwiYSI6ImNrZnJiMDMxbDA0aGsyenFlajhvMzZ4bXUifQ.I7l7fJBAHCQWRwyYozq4ZQ")

```


```{r eval=T}
loc_name <- "Union"

loc2use <- "Schenectady, NY"
country <- "US"

state2use <- "NY"
county2use <- "Schenectady"



lat_pt <- 42.8166477
long_pt <- -73.9297887
```


```{r eval = T}
bb_values <- getbb(loc2use)

bb_values
```
```{r}
#42.8166477,-73.9297887
#42.3605748,-71.0943991


coord_buffer <- 0.007 


bb_values[1,1] <- long_pt - coord_buffer*1.5
bb_values[1,2] <- long_pt + coord_buffer*1.5

bb_values[2,1] <- lat_pt - coord_buffer
bb_values[2,2] <- lat_pt + coord_buffer
```


```{r}
if (country == "US") {
  Water_features <- area_water(state = state2use, county = county2use)  # download the data

Water_features <- st_as_sf(Water_features) # convert to an sf object

Linear_water <- linear_water(state = state2use, county = county2use)  # download the data

Linear_water <- st_as_sf(Linear_water) # convert to an sf object
}


```


```{r}
buildings <- bb_values %>%
  opq()%>%
  add_osm_feature(key = "building") %>%
  osmdata_sf()

buildings
```

```{r}
streets <- bb_values %>%
  opq()%>%
  add_osm_feature(key = "highway", 
                  value = c("motorway", "primary", 
                            "secondary", "tertiary")) %>%
  osmdata_sf()
streets
```


```{r}
small_streets <- bb_values %>%
  opq()%>%
  add_osm_feature(key = "highway", 
                  value = c("residential", "living_street",
                            "unclassified",
                            "service", "footway")) %>%
  osmdata_sf()

river <-  bb_values %>%
  opq()%>%
  add_osm_feature(key = "waterway", value = "river") %>%
  osmdata_sf()
```



```{r}
ggplot() +
  
  geom_sf(data = buildings$osm_polygons,
          inherit.aes = FALSE,
          color = "grey",
          fill = "white",
          size = .4,
          alpha = 1) +
  
  #7fc0ff
  geom_sf(data = streets$osm_lines,
          inherit.aes = FALSE,
          color = "white",
          size = .8,
          alpha = .8) +
  
  #ffbe7f
  geom_sf(data = small_streets$osm_lines,
          inherit.aes = FALSE,
          color = "white",
          size = .4,
          alpha = .6) +
  
  #blue
  # geom_sf(data = river$osm_lines,
  #         inherit.aes = FALSE,
  #         color = "white",
  #         size = .4,
  #         alpha = 1) + 
  
  geom_sf(data = Linear_water,
          color = "lightgrey") +         
  
  geom_sf(data = Water_features,
          fill = "lightgrey") + 
  coord_sf(xlim = c(bb_values[1,1], bb_values[1,2]), 
           ylim = c(bb_values[2,1], bb_values[2,2]),
           expand = FALSE) +

  theme_void() +
  theme(plot.background = element_rect(fill = "#282828"))
```

```{r}
ggsave(paste(loc_name,"_black_background_pom.png", sep = ""), 
       width = 6, height = 6,
       dpi = 1200)
```



```{r}
map_2 <- ggplot() +
  
  geom_sf(data = buildings$osm_polygons,
          inherit.aes = FALSE,
          #color = "black",
          fill = "black",
          size = 0,
          alpha = 1) +
  
  #7fc0ff
  geom_sf(data = streets$osm_lines,
          inherit.aes = FALSE,
          color = "grey",
          size = 0.8,
          alpha = 1) +
  
  #ffbe7f
  geom_sf(data = small_streets$osm_lines,
          inherit.aes = FALSE,
          color = "grey",
          size = 0.4,
          alpha = 1) +
  
  #blue
  
  geom_sf(data = Linear_water,
          size = 1.0,
          color = "grey86") +         
  
  geom_sf(data = Water_features,
          fill = "grey86", color = NA) + 
  
  coord_sf(xlim = c(bb_values[1,1], bb_values[1,2]), 
           ylim = c(bb_values[2,1], bb_values[2,2]),
           expand = FALSE) +

  theme_void() +
  theme(plot.background = element_rect(fill = "white")) 

map_2
  
```


```{r}
#fname <- str_replace(loc2use, pattern = ", ", replacement = "_")

ggsave(paste(loc_name,"_white_background.png", sep = ""), 
       width = 6, height = 6,
       dpi = 1200)
```


```{r}
map_2 + theme_pomological_fancy("Homemade Apple", 16) +
    theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

```{r}
#fname <- str_replace(loc2use, pattern = ", ", replacement = "_")

ggsave(paste(loc_name,"_antique_background.png", sep = ""), 
       width = 6, height = 6,
       dpi = 1200)
```


```{r}
tmap_mode("view") 
tm_shape(buildings$osm_polygons) +
  tm_polygons() +

tm_shape(streets$osm_lines) +
  tm_lines() +
  
tm_shape(small_streets$osm_lines) +
  tm_lines() 
```










